### ISSUE TITLE
Bug: Copied objects not in preview / workspace in Laser

### ISSUE THREAD

**Issue by HorstBaerbel** [Snapmaker/Luban#1617]
# 🐞 bug report

### Affected Version(s)
4.3.0

### Is this a regression? (optional)
no idea

### To Reproduce
1. Add objects from svg (see attached file), assign different tool paths or load snaplzr file
2. Duplicate objects (Mirror or not, does not matter)
4. Go to preview and / or workspace
![grafik](https://user-images.githubusercontent.com/1310747/172668088-92af2505-671f-4213-ad2a-e04e7a36179f.png)

### Exception or Error (optional)
Only one object is on preview and workspace
![grafik](https://user-images.githubusercontent.com/1310747/172668924-01020d01-5592-401d-a885-899838ba7f8d.png)

### Expected behavior
Copied object should be visible in preview and export to workspace

## 🌍  Your Environment

**Platform:**
- Operating System: Fedora 36
- Printer: Snapmaker 2.0 A350T

[Bug_again.zip](https://github.com/Snapmaker/Luban/files/8863422/Bug_again.zip)

**Comment by sumibin** [comment]
This issue should have been fixed.

**Comment by HorstBaerbel** [comment]
Error still in 4.7.2. Can be tested with same files. Please reopen.
