### ISSUE TITLE
Bug: Luban crashes when creating toolpath for laser

### ISSUE THREAD

**Issue by Walshe-d** [Snapmaker/Luban#2015]
# 🐞 bug report

### Affected Version(s)

 The issue is caused by version 4.6.3

### Is this a regression? (optional)

 Yes, the previous version in which this bug was not present was definitely 4.3.2, I'm not sure if versions between 4.3.2 and 4.6.2. had this issue

### To Reproduce
1. Go to luban, laser, 3 axis, insert text. The word snapmaker will appear.
2. Click on 'next'
3. Click on the text and then click on create tool path
4. The app crashes with no error code
 Luban crashes when I try to create a tool path for text.
![Image_3](https://user-images.githubusercontent.com/34304439/222814446-0664cc24-517f-492f-9337-bb687c0a64ae.png)

Exception or Error (optional)
<pre><code>

There is no error code
</code></pre>

Expected behavior

I expect the toolpath to be created

## 🌍  Your Environment

**Platform:**
<pre><code>

- Operating System: [Ubuntu 20.04.5 LTS]
- Printer: [Snapmaker Original]

</code></pre>

**Comment by Walshe-d** [comment]
When luban prompts to specify what printer you are working with if you choose snapmaker original **with** module extension this error will occur. 

However, if you use the snapmaker original **without** module extension, this error does not occur.

This actually probably wasn't an issue with v4.6.3 apologies

**Comment by parachvte** [comment]
Bug confirmed on v4.6.3, Ubuntu 20.04 LTS.

It should be fixed in v4.7.0 now. I'm closing the issue.

**Comment by Watson-Sei** [comment]
No, the problem still occurs.
It occurs in Snapmaker Luban 4.9.1 when creating toolpaths for CNC 3-axis.
<img width="867" alt="スクリーンショット 2023-10-17 12 54 16" src="https://github.com/Snapmaker/Luban/assets/55475145/994a5bc9-8a81-43d3-b409-60dbd384038a">

**Comment by Watson-Sei** [comment]
@parachvte 
No, the problem still occurs.
It occurs in Snapmaker Luban 4.9.1 when creating toolpaths for CNC 3-axis.
<img width="882" alt="スクリーンショット 2023-10-17 12 53 29" src="https://github.com/Snapmaker/Luban/assets/55475145/03d2648d-59c1-4ad7-8b9b-484f632e0a20">

**Comment by ExtraZiadeh** [comment]
@parachvte 

I can confirm with @Watson-Sei that this is still an issue with Luban 4.9.1
