### ISSUE TITLE
Luban 3.15.0 - echo:Unknown command: "M1011"

### ISSUE THREAD

**Issue by Mortisaga** [Snapmaker/Luban#978]
I installed 3.15.0 - when I connect Luban via USB (Com-port) I get the message "echo:Unknown command: "M1011" ".
It does not appear by connecting via WiFi.

**Comment by parachvte** [comment]
Confirmed bug. Should be fixed ASAP.

**Comment by Mortisaga** [comment]
Thank you for the fast response. I did not find something in the formum - now I see, this post was created 1h after I posted here. For the devs - is it better to post issues/possible bugs in the snapmaker forum or at github?

**Comment by parachvte** [comment]
> For the devs - is it better to post issues/possible bugs in the snapmaker forum or at github?

Both. Feedback on forum will go back to our backlog as well. 
On the forum you will have our kindly technical support collecting and tracking the issues. Especially when you don't know where the issue locates (Luban / firmware / hardware).
On Github you will get direct feedback from devs, track issue status.

**Comment by christophepersoz** [comment]
Same here

**Comment by parachvte** [comment]
The issue should be fixed in versions >= 3.15.2

**Comment by Mortisaga** [comment]
the problem still remains in 4.1.2 (or it returned), now it is M1012

![grafik](https://user-images.githubusercontent.com/79230540/147097093-a9a25f22-bf24-44e1-bd77-06fb906320c5.png)
